### ISSUE TITLE
Починить фид подкаста

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/podcast#31]
Валидатор фидов W3C совсем не рад, есть [несколько претензий](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fweb-standards.ru%2Fpodcast%2Ffeed%2F).

Если возьмётесь — напишите!

**Внимание!** Есть вероятность, что претензии насчёт iTunes левые и просто валидатор устарел немного.

**Comment by pepelsbey** [comment]
@zamkevich починил со слэшем в конце, проверите?

https://web-standards.ru/podcast/feed теперь должен редиректить на https://web-standards.ru/podcast/feed/

**Comment by zamkevich** [comment]
@pepelsbey проверил, редирект работает. 
Вадим, а для чего вы простите проверить такую простую вещь?

**Comment by pepelsbey** [comment]
@zamkevich спасибо

**Comment by alexeyten** [comment]
Что-то я тут поэкспериментировал и вроде шоу ноуты всё-таки берутся из `description`. И `itunes:summary` берётся только короткая заметка для списка эпизодов.
При этом Overcast показывает `itunes:summary` сплошным текстом перед `description`.

**Comment by alexeyten** [comment]
WIP 🚧 
![F3108EF3-C9DC-418A-AC01-AC73980F9B39](https://user-images.githubusercontent.com/44377/150533149-e46add18-a3b1-4250-bf72-67b8eba4f0db.jpeg)
![BA620A7F-B96D-4826-B105-51B5E8F357A8](https://user-images.githubusercontent.com/44377/150533157-3265d13f-0e8a-4308-99d7-bf152d8c12d9.jpeg)
![49B3A5CB-CBB2-41EB-AED4-3EDC3A37AA96](https://user-images.githubusercontent.com/44377/150533162-a517f6c9-b3ac-49e3-9d23-2509041105ab.png)
![3FCEF1A1-0EE8-484F-865E-D085BFD9414A](https://user-images.githubusercontent.com/44377/150533171-2131e4e9-e80d-4f35-9f28-aa00e47eb055.png)

**Comment by alexeyten** [comment]
<details>
<summary>Overcast вариант 1</summary>

![photo_2022-01-21_16-29-29](https://user-images.githubusercontent.com/44377/150535370-d5e53768-ab03-4df2-be84-18dc872d191e.jpg)
![photo_2022-01-21_16-29-38](https://user-images.githubusercontent.com/44377/150535367-4979fd05-507f-46bf-b291-953d9b5706d9.jpg)
</details>

<details>
<summary>Overcast вариант 2</summary>

![photo_2022-01-21_16-29-42](https://user-images.githubusercontent.com/44377/150535489-b7f8ce73-3c5f-4fdf-bd0a-92082c609757.jpg)
![photo_2022-01-21_16-29-46](https://user-images.githubusercontent.com/44377/150535485-808e2dd4-b72b-4d8a-ac71-86c12c03db7c.jpg)
</details>

<details>
<summary>Google Podcasts вариант 1</summary>

![photo_2022-01-21_16-32-39](https://user-images.githubusercontent.com/44377/150535882-c2bc0a61-ab5b-4012-8d0f-6b082779eb02.jpg)
![photo_2022-01-21_16-32-46](https://user-images.githubusercontent.com/44377/150535912-2c0843a5-896e-43bf-9148-4b2f5f80e8e9.jpg)
</details>

<details>
<summary>Google Podcasts вариант 2</summary>

![photo_2022-01-21_16-32-51](https://user-images.githubusercontent.com/44377/150536063-8352102d-ddfb-41be-875d-cd33308af50f.jpg)
![photo_2022-01-21_16-28-15](https://user-images.githubusercontent.com/44377/150536117-8ea46276-9887-48c6-8b30-e02efc023ac3.jpg)
</details>

<details>
<summary>Castro вариант 1</summary>

![photo_2022-01-21_16-36-18](https://user-images.githubusercontent.com/44377/150536255-b8ad13bb-86ea-49f1-8c7a-78904a266c57.jpg)
![photo_2022-01-21_16-36-23](https://user-images.githubusercontent.com/44377/150536295-91ab3aa9-4300-43fd-a194-6ea25a89a134.jpg)
</details>

<details>
<summary>Castro вариант 2</summary>

![photo_2022-01-21_16-37-26](https://user-images.githubusercontent.com/44377/150536361-06908671-e66b-43e3-af5b-f049e379691e.jpg)
![photo_2022-01-21_16-37-29](https://user-images.githubusercontent.com/44377/150536378-06be7cf2-c165-4aa5-88a3-4bfba6c6afdc.jpg)
</details>

**Comment by pepelsbey** [comment]
@alexeyten крутота :) А что в итоге нужно сделать, в двух словах?

**Comment by alexeyten** [comment]
Если кратко, то в 1 варианте я по сути просто откатил изменение https://github.com/web-standards-ru/podcast/commit/2c17d4108f9a7ddd6a542fd715f72c0a1b260a1e
Возможно в мае у приложения Apple был какой-то глюк (и вообще я подозреваю что это была бета какая-нибудь)

Во втором варианте переложил заголовок (`episode.data.title`) в `<itunes:summary>` и в начало `<description>`, потому что саммари не показывается внутри одного эпизода.

**Comment by pepelsbey** [comment]
Откатил дублирование описания в `<itunes:summary>`, оставил там только краткое описание

```
<itunes:summary>{{ episodeSummary | trim }}</itunes:summary>
```

Посмотрим, что получится. Спасибо @alexeyten за расследование!

**Comment by pepelsbey** [comment]
Починили
