### ISSUE TITLE
313

### ISSUE THREAD

**Issue by oleg3280** [web-standards-ru/podcast#55]
Добрый вечер. Хотел прослушать последний подкаст, но после 15 минуты ползунок сбрасывается на конец файла и воспроизведение прерывается. Олег.

**Comment by oleg3280** [comment]
Извините, уже всё работает. Это мой первый баг-репорт. Поспешил. Спасибо за подкасты. Олег.

**Comment by pepelsbey** [comment]
Привет! Спасибо за репорт, пишите в следующий раз сразу в чат — так оперативнее починим

https://t.me/webstandards_chat
